server:
  port: 9090
spring:
  application:
    name: book-my-ticket
  datasource:
    url: jdbc:mysql://localhost:3306/book-my-tickets?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  data:
    redis:
      url: redis://localhost:6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: saishkulkarni7@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
admin:
  email: admin@gmail.com
  password: admin

cloudinary:
  cloud-name: dc0e7ovcp
  api-key: 864894457858136
  api-secret: D1MEnh--WVZECh2yqac7fEM1C1Q